server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Serve static files (css, js)
    location ~* \.(?:css|js|ico|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    # Fallback for HTML files (optional)
    location / {
        try_files $uri $uri/ =404;
    }
}
